resources:
- name: cargalibre-1
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/localizadores-444314/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: projects/debian-cloud/global/images/family/debian-11
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/localizadores-444314/global/networks/default
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          sudo mkdir -p /home/labs
          cd /home/labs
          sudo git clone https://github.com/Marcosespa/CargaLibre-Rutix.git
          cd CargaLibre-Rutix
          sudo apt update
          sudo apt upgrade -y
          sudo apt install git
          sudo apt install python3 python3-pip -y
          sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo git clone https://github.com/Marcosespa/CargaLibre-Rutix.git /home/labs/CargaLibre-Rutix

- name: cargalibre-2
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/localizadores-444314/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: projects/debian-cloud/global/images/family/debian-11
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/localizadores-444314/global/networks/default
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          sudo mkdir -p /home/labs
          cd /home/labs
          sudo git clone https://github.com/Marcosespa/CargaLibre-Rutix.git
          cd CargaLibre-Rutix
          sudo apt update
          sudo apt upgrade -y
          sudo apt install python3 python3-pip -y

- name: cargalibre-3
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/localizadores-444314/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: projects/debian-cloud/global/images/family/debian-11
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/localizadores-444314/global/networks/default
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          sudo mkdir -p /home/labs
          cd /home/labs
          sudo git clone https://github.com/Marcosespa/CargaLibre-Rutix.git
          cd CargaLibre-Rutix
          sudo apt update
          sudo apt upgrade -y
          sudo apt install python3 python3-pip -y
